[package]
name = "axum-auth-utils"
version = "0.0.1"
edition = "2024"

[dependencies]
axum = "0.8.6"
tokio = { version = "1.0", features = ["full"]}

cookie-monster = { path = "../cookie-monster", features = ["axum" ]}

anyhow = "1.0.100"

uuid = { version = "1.18.1", features = ["v7"] }

oauth2 = { version = "5.0.0", features = ["reqwest"], default-features = false }
