[package]
name = "axum-security-macros"
version = "0.0.1"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", default-features = false }
quote = { version = "1.0", default-features = false }
