[package]
name = "axum-security"
version = "0.0.1"
edition = "2024"

[dependencies]
axum = { version = "0.8.6", features = ["macros" ]}
tokio = { version = "1.0", features = ["full"]}
tower = "0.5"

cookie-monster = { path = "../../cookie-monster", features = ["axum" ]}
jsonwebtoken = { version = "10.2.0", features = ["aws_lc_rs"] }

anyhow = "1.0.100"

uuid = { version = "1.18.1", features = ["v7"] }

oauth2 = { version = "5.0.0", features = ["reqwest", "rustls-tls"], default-features = false }

serde = { version = "1.0.228", features = ["derive"] }

axum-security-macros = { path = "../axum-security-macros" }

[dev-dependencies]
axum = { version = "0.8.6", features = ["macros" ]}
tokio = { version = "1.0", features = ["full"]}
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.9.0-alpha.1", features = ["sqlite"] }

